### PR TITLE
viewing and modifying

### PR DESCRIPTION
**Pull request by madhavkbinoy**

### CODE REVIEW

**Comment by AlaynaMonteiro** [comment]
```text
main.c: In function ‘main’:
main.c:41:13: error: implicit declaration of function ‘display_gradecard’ [-Wimplicit-function-declaration]
   41 |             display_gradecard(students, n);
      |             ^~~~~~~~~~~~~~~~~
make: *** [Makefile:7: main.o] Error 1
```
@madhavkbinoy FIx this is 15 minutes or else I will deassign you

**Comment by madhavkbinoy** [comment]
Please give me a little more time, I am working on my logic.

**Comment by madhavkbinoy** [comment]
I have made the changes please look into it, Thank you.

**Comment by AlaynaMonteiro** [comment]
```text
main.c: In function ‘main’:
main.c:44:13: error: implicit declaration of function ‘ViewRecords’ [-Wimplicit-function-declaration]
   44 |             ViewRecords();
      |             ^~~~~~~~~~~
main.c:47:13: error: implicit declaration of function ‘ModifyRecord’ [-Wimplicit-function-declaration]
   47 |             ModifyRecord();
      |             ^~~~~~~~~~~~
make: *** [Makefile:7: main.o] Error 1
```

**Comment by AlaynaMonteiro** [comment]
Would you like more time to fix these issues or should I deassign you?

**Comment by madhavkbinoy** [comment]
I ran the following command on macOS , n it ran without errors

gcc main.c functions.c -o main
./main

**Comment by AlaynaMonteiro** [comment]
Which sem hall are you in? I'd like to see it

**Comment by madhavkbinoy** [comment]
I have made the changes

**Comment by AlaynaMonteiro** [comment]
The student data is not persistent in the same session. Although, you have implement view data correctly and so I shall assign you some points. The modify feature does not update some of the fields.

**Comment by AlaynaMonteiro** [comment]
!bounty 40

**Pull request closed without merging**
